""""""""""Vundle Config"""""""""""""""""""""""""""""""""""""
set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

"syntax checking
"Plugin 'scrooloose/syntastic'

"smart status line
Plugin 'vim-airline/vim-airline-themes'
Plugin 'vim-airline/vim-airline'
Plugin 'bling/vim-bufferline'

"git version status
Plugin 'tpope/vim-fugitive'

"session management
"Plugin 'xolox/vim-session'
"Plugin 'xolox/vim-misc'

"syntax checking and auto complete
"C++
Plugin 'Valloric/YouCompleteMe'
"Python
"Plugin 'davidhalter/jedi-vim'

"promptline bash
Plugin 'edkolev/promptline.vim'

"cohama lexima auto closing
Plugin 'cohama/lexima.vim'

"Outline viewer
"Plugin 'majutsushi/tagbar'

"File Tree
"Plugin 'scrooloose/nerdtree'

"Manipulate file
"Plugin 'kien/ctrlp.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
""""""""""My Non-Plugin Config""""""""""""""""""""""""""""""
syntax on
set nu
set cindent smartindent
" use Google's coding style --- two space indent
set sm ts=2 sw=2
"set fdm=syntax
set hls is ruler
"set mouse=a
set cst
set tw=80
ab #b /*------------------------------*
ab #e *------------------------------*/
"set paste
"pasting text unmodified from other applications
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

"my color scheme
colorscheme mac
"colorscheme mine
"colorscheme mymolokai

""""""""""Plugin Config"""""""""""""""""""""""""""""""""""""
"""""Syntastic Config""""""""""""""""""
"let g:syntastic_cpp_compiler = 'clang++'
"let g:syntastic_cpp_compiler_options = ' -std=c++11 -stdlib=libc++'

"""""Airline Config""""""""""""""""""
"always show status line
set laststatus=2
"enable airline extension
let g:airline#extensions#tabline#enabled = 1
"customize airline layout
set encoding=utf-8
" powerline symbols
" download powerline fonts from
" https://github.com/powerline/fonts
" Powerline fonts are compatible with both osx and linux.
" Set the terminal fonts to make following symbols properly displayed.
let g:airline_powerline_fonts = 1
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
if !exists('g:airline_symbols')
	let g:airline_symbols = {}
endif
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

"""""YCM Config""""""""""""""""""
"solve the ycm Value Error problem
let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
let g:ycm_autoclose_preview_window_after_completion=1
nnoremap <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>

"""""Jedi-Vim Config""""""""""""""""""
let g:jedi#goto_command = "<leader>d"
let g:jedi#goto_assignments_command = "<leader>g"
let g:jedi#goto_definitions_command = ""
let g:jedi#documentation_command = "K"
let g:jedi#usages_command = "<leader>n"
let g:jedi#completions_command = "<C-Space>"
let g:jedi#rename_command = "<leader>r"

"show/hide tagbar window
"TagbarToggle

"show/hide the Nerdtree window
"NERDTreeToggle
"
"""""Lexima Config""""""""""""""""""
call lexima#add_rule({'char': '$', 'input_after': '$', 'filetype': 'tex'})
call lexima#add_rule({'char': '$', 'at': '\%#\$', 'leave': 1, 'filetype': 'tex'})
call lexima#add_rule({'char': '<BS>', 'at': '\$\%#\$', 'delete': 1, 'filetype': 'tex'})
